### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by judicius** [mrp-v2/VersatilePortals#1]
Not sure what's causing this.
`08.12 12:28:26 [Server] Server thread/ERROR [mr.ve.VersatilePortals/]: No key RemainingPortalCooldown in MapLike[{InPortalTime:0,PortalCooldown:0}]`

`08.12 12:35:18 [Server] Server thread/ERROR [mr.ve.VersatilePortals/]: No key RemainingPortalCooldown in MapLike[{InPortalTime:0,PortalCooldown:0}]`

`08.12 12:35:18 [Server] Server thread/ERROR [mr.ve.VersatilePortals/]: No key RemainingPortalCooldown in MapLike[{InPortalTime:0,PortalCooldown:0}]`

Forge 35.1.4
Versatileportasl 2.1.0.0

**Comment by mrp-v2** [comment]
Did you recently upgrade your Versatile Portals version?

**Comment by judicius** [comment]
yup to 2.1.0.0, today in fact.

**Comment by mrp-v2** [comment]
This is a known issue when upgrading to 2.1.0.0 or above from a previous version. The way the mod stores data changed between versions, which leads to log spam. Unfortunately, there isn't really a work-around. What will prevent this issue is making a new world. If that isn't an option, you can try using commands to edit the entity data, but I don't know much about that, so I couldn't help you do it.
