### ISSUE TITLE
Crashing to CTD because of Tool Error with Minecolonies

### ISSUE THREAD

**Issue by judicius** [mrp-v2/VersatilePortals#2]
Issue reported with Minecolonies team https://github.com/ldtteam/minecolonies/issues/6286

Game crashed to desktop when interacting with a Minecolonies NPC. Minecolonies team is saying it has to do with something in the mod being labeled as a tool but not properly acting as a tool.

Forge 35.1.13
MC 1.16.4
Minecolonies 0.13.535 ALPHA
Structurize 0.13.104 ALPHA
MRPlibrary 1.3.0.1
Versatile Portals 2.2.02

Crashlog https://gist.github.com/judicius/dfd262776fa677c4e71012b969b80078
Latest https://gist.github.com/judicius/c13648f37f160a5dd59c0f88e70d39ed

**Comment by fd245896724956** [comment]
I am getting this error as well. Seems possibly related to this line which is adding tool types to the block items: https://github.com/mrp-v2/VersatilePortals/blob/1a5fbbe609822fe2bddd24c969a17d87f6877168/src/main/java/mrp_v2/versatileportals/util/ObjectHolder.java#L116

I tried building locally to confirm but the gradle build fails because it doesn't have the password for the mrplibrary maven.

**Comment by mrp-v2** [comment]
I've now uploaded a new version of Versatile Portals. Please let me know if it fixes the issue.

**Comment by judicius** [comment]
New version tested in the same minimalist environment causes CTD, no crash log output but log output attached.

https://gist.github.com/judicius/f3365c7c09e113f4de290ea7cec6bf39

**Comment by mrp-v2** [comment]
oops, I messed up the mods.toml version range

**Comment by mrp-v2** [comment]
I've uploaded another version that should finally work. Please let me know if it fixes the issue.

**Comment by fd245896724956** [comment]
I can confirm that version 2.3.0.1 does not crash in my game, thank you for the fix.
